#!/usr/bin/env bash

apt update
apt -y upgrade
apt -y install autopoint bison flex gettext libpam0g-dev libtool make
apt -y autoremove

cd /usr/src/
rm -r *
wget https://github.com/baklanomax/kbd/archive/refs/tags/v2.4.0-mod.tar.gz
tar -zxf v2.4.0-mod.tar.gz
rm v2.4.0-mod.tar.gz
mv kbd-2.4.0-mod/ kbd/
cd kbd/

./autogen.sh
./configure
make
make install-strip

cd ..
rm -r *

echo -e "\n\n\nУстановка kbd успешно завершена."
