#!/usr/bin/env bash

apt update
apt -y upgrade
apt -y install bc bison dwarves flex make libelf-dev libssl-dev
apt -y autoremove

cd /usr/src/
rm -r *
wget https://github.com/baklanomax/linux/archive/refs/tags/v5.13-fixkeys.tar.gz
tar -zxf v5.13-fixkeys.tar.gz
rm v5.13-fixkeys.tar.gz
mv linux-5.13-fixkeys/ linux/
cd linux/
#make olddefconfig




#sudo make nconfig
#General setup —> Build ID Salt —> "5.13"
#Cryptographic API —> Certificates for signature checking —> Additional X.509 keys for default system keyring —> ""




#make -j $(nproc)
#sudo make INSTALL_MOD_STRIP=1 modules_install
#sudo make install

#echo -e "\n\n\nУстановка ядра успешно завершена."
