#!/usr/bin/env bash

apt update
apt -y upgrade
apt -y install bc bison dwarves flex make libelf-dev libssl-dev
apt -y autoremove

cd /usr/src/
rm -r *
wget https://github.com/baklanomax/linux/archive/refs/tags/v5.15-mod.tar.gz
tar -zxf v5.15-mod.tar.gz
rm v5.15-mod.tar.gz
mv linux-5.15-mod/ linux/
cd linux/

make olddefconfig
sed -i "s/CONFIG_BUILD_SALT.*/CONFIG_BUILD_SALT=\"5.15.0-amd64\"/; s/.*CONFIG_I2C_HID_ACPI.*/CONFIG_I2C_HID_ACPI=m/; s/CONFIG_SYSTEM_TRUSTED_KEYS.*/CONFIG_SYSTEM_TRUSTED_KEYS=\"\"/" .config
make -j $(nproc)
make INSTALL_MOD_STRIP=1 modules_install
make install

cd ..
rm -r *

echo -e "\n\n\nУстановка ядра успешно завершена."
