#!/usr/bin/env bash

apt update
apt -y upgrade
apt -y install install bc bison dwarves flex make libelf-dev libssl-dev
apt -y autoremove

cd /usr/src/

rm


wget https://github.com/baklanomax/linux/archive/refs/tags/v5.13-fixkeys.tar.gz
tar -zxf v5.13-fixkeys.tar.gz
rm v5.13-fixkeys.tar.gz
mv linux-5.13-fixkeys/ linux/
cd linux/
make olddefconfig




#sudo make nconfig
#General setup —> Build ID Salt —> "5.13"
#Cryptographic API —> Certificates for signature checking —> Additional X.509 keys for default system keyring —> ""





#make -j $(nproc)




#sudo make INSTALL_MOD_STRIP=1 modules_install
#sudo make install





#cat bash.bashrc > /etc/bash.bashrc
#cat console-setup > /etc/default/console-setup
#cat daemon.conf > /etc/gdm3/daemon.conf
#cat grub > /etc/default/grub
#cat logind.conf > /etc/systemd/logind.conf

#mkdir /etc/systemd/system/getty@tty{3..15}.service.d/ &> /dev/null
#cat override_root.conf > /etc/systemd/system/getty@tty3.service.d/override.conf
#cat override_user.conf | tee /etc/systemd/system/getty@tty{4..12}.service.d/override.conf &> /dev/null
#cat override_devel.conf | tee /etc/systemd/system/getty@tty{13..15}.service.d/override.conf &> /dev/null

#chmod u+s /usr/sbin/kbdrate
#update-grub

echo -e "\n\n\nУстановка ядра успешно завершена."
