#!/usr/bin/env bash

while true
do
	read -ep "Исправить ссылки на раздел подкачки? [y/n] " swap
	if [[ $swap == "y" ]] || [[ $swap == "n" ]]
	then
		break
	fi
done
while true
do
	read -ep "Установить почтовый клиент? [y/n] " mail
	if [[ $mail == "y" ]] || [[ $mail == "n" ]]
	then
		break
	fi
done
while true
do
	read -ep "Выполнить основные настройки? [y/n] " tune
	if [[ $tune == "y" ]] || [[ $tune == "n" ]]
	then
		break
	fi
done
while true
do
	read -ep "Установить пакет kbd с модифицированной командой showkey? [y/n] " kbd
	if [[ $kbd == "y" ]] || [[ $kbd == "n" ]]
	then
		break
	fi
done
while true
do
	read -ep "Установить ядро Linux с модифицированным клавиатурным вводом? [y/n] " kernel
	if [[ $kernel == "y" ]] || [[ $kernel == "n" ]]
	then
		break
	fi
done

if [[ $mail == "y" ]]
then
	read -ep "Введите имя учётной записи для Mail.ru: " login
	read -ep "Введите пароль для Mail.ru: " password
	read -ep "Введите имя отправителя для почтового клиента: " name
fi
if [[ $tune == "y" ]] || [[ $kernel == "y" ]]
then
	while true
	do
		read -ep "Введите имя учётной записи для пользователя: " user
		if [[ $(id -un $user 2> /dev/null) == $user ]]
		then
			break
		else
			adduser --disabled-login --gecos "" $user 2> /dev/null && break || echo "Ошибка: недопустимое имя учётной записи"
		fi
	done
fi

if [[ $swap == "y" ]]
then
	uuid=$(lsblk -n -o UUID,FSTYPE | grep swap | cut -d " " -f 1)
	sed -i "s/UUID=.* none/UUID=$uuid none/" /etc/fstab
	echo "RESUME=UUID=$uuid" > /etc/initramfs-tools/conf.d/resume
	update-initramfs -u -k all
fi

if [[ $mail == "y" ]] || [[ $tune == "y" ]] || [[ $kbd == "y" ]] || [[ $kernel == "y" ]]
then
	apt update
	apt -y upgrade
	if [[ $mail == "y" ]]
	then
		apt -y install mutt
	fi
	if [[ $tune == "y" ]]
	then
		apt -y install gpm mc tmux
	fi
	if [[ $kbd == "y" ]] || [[ $kernel == "y" ]]
	then
		apt -y install bison flex make
	fi
	if [[ $kbd == "y" ]]
	then
		apt -y install autopoint gettext libpam0g-dev libtool
	fi
	if [[ $kernel == "y" ]]
	then
		apt -y install bc dwarves libelf-dev libssl-dev
	fi
	apt -y autoremove
fi

if [[ $mail == "y" ]]
then
	sed "s/ivanov/$login/g; s/password/$password/g; s/Ivan Ivanov/$name/" files/Muttrc > /etc/Muttrc
fi

if [[ $tune == "y" ]]
then
	mkdir -m 700 /root/{.config/,.config/mc/}
	sudo -u $user mkdir -m 700 /home/$user/{.config/,.config/mc/}
	cp files/ini /root/.config/mc/
	sudo -u $user cp files/ini /home/$user/.config/mc/

	cp files/console-setup /etc/default/
	sed "s/=user/=$user/" files/daemon.conf > /etc/gdm3/daemon.conf
	cp files/inputrc /etc/
	cp files/grub /etc/default/
	cp files/linuxtune.sh /etc/profile.d/
	cp files/logind.conf /etc/systemd/

	mkdir /etc/systemd/system/getty@tty{3..15}.service.d/
	sed "s/user/$user/" files/override.conf | tee /etc/systemd/system/getty@tty{3..15}.service.d/override.conf &> /dev/null

	sudo -u $user dbus-launch gsettings set org.gnome.desktop.peripherals.keyboard delay 2000
	sudo -u $user dbus-launch gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 110
	sudo -u $user dbus-launch gsettings set org.gnome.desktop.screensaver lock-delay 0
	sudo -u $user dbus-launch gsettings set org.gnome.desktop.screensaver lock-enabled false

	chmod u+s /usr/sbin/kbdrate
	update-grub
fi

if [[ $kernel == "y" ]]
then
	id=$(id -u $user)
	sed "s/1000/$id/" files/keysound > /usr/local/bin/keysound
	chmod +x /usr/local/bin/keysound

	cp files/change-keysound-* /usr/local/sbin/
	chmod +x /usr/local/sbin/change-keysound-*

	mkdir /usr/share/keysound/
	cp -r sounds/ /usr/share/keysound/
fi

if [[ $kbd == "y" ]]
then
	cd /usr/src/
	wget https://github.com/baklanomax/kbd/archive/refs/tags/v2.5.0-mod.tar.gz
	tar -zxf v2.5.0-mod.tar.gz
	rm -r kbd/ v2.5.0-mod.tar.gz
	mv kbd-2.5.0-mod/ kbd/
	cd kbd/

	./autogen.sh
	./configure
	make
	make install-strip
fi

if [[ $kernel == "y" ]]
then
	cd /usr/src/
	wget https://github.com/baklanomax/linux/archive/refs/tags/v5.18-mod.tar.gz
	tar -zxf v5.18-mod.tar.gz
	rm -r linux/ /usr/lib/modules/*[!4]/ v5.18-mod.tar.gz
	rm /boot/*[!4]
	mv linux-5.18-mod/ linux/
	cd linux/
	sed -i "s/\"user/\"$user/" drivers/tty/vt/keyboard.c

	config=$(ls /boot/config-* | tail -n 1)
	cp $config .config
	make olddefconfig
	sed -i "s/.*CONFIG_BUILD_SALT.*/CONFIG_BUILD_SALT=\"5.18.0-amd64\"/; s/.*CONFIG_I2C_HID_ACPI.*/CONFIG_I2C_HID_ACPI=m/; \
		s/.*CONFIG_SYSTEM_TRUSTED_KEYS.*/CONFIG_SYSTEM_TRUSTED_KEYS=\"\"/" .config
	make -j $(nproc)
	make INSTALL_MOD_STRIP=1 modules_install
	make install
fi

echo -e "\n\n\nНастройка успешно завершена."
