#!/usr/bin/env bash

cat sources.list > /etc/apt/sources.list

apt update
apt -y upgrade
apt -y install firmware-atheros gpm mc vim 
apt -y autoremove

cat bash.bashrc > /etc/bash.bashrc
cat console-setup > /etc/default/console-setup
cat daemon.conf > /etc/gdm3/daemon.conf
cat inputrc > /etc/inputrc
cat grub > /etc/default/grub
cat logind.conf > /etc/systemd/logind.conf

mkdir /etc/systemd/system/getty@tty{3..15}.service.d/
cat override_root.conf | tee /etc/systemd/system/getty@tty{3,4}.service.d/override.conf &> /dev/null
cat override_user.conf | tee /etc/systemd/system/getty@tty{5..13}.service.d/override.conf &> /dev/null
cat override_devel.conf | tee /etc/systemd/system/getty@tty{14,15}.service.d/override.conf &> /dev/null

chmod u+s /usr/sbin/kbdrate
update-grub

echo -e "\n\n\nНастройка успешно завершена."
