#!/usr/bin/env bash

if
then
	sed -i "s/.*CONFIG_BUILD_SALT.*/CONFIG_BUILD_SALT=\"5.16.0-amd64\"/; s/.*CONFIG_I2C_HID_ACPI.*/CONFIG_I2C_HID_ACPI=m/" /usr/local/bin/keysound
else
	sed -i "s/.*CONFIG_BUILD_SALT.*/CONFIG_BUILD_SALT=\"5.16.0-amd64\"/; s/.*CONFIG_I2C_HID_ACPI.*/CONFIG_I2C_HID_ACPI=m/" /usr/local/bin/keysound
fi
